FredHutch/Oncoscape

Dockerfile, Oncoscape/inst/scripts/apps/oncoscape/makefile, makefile
@LisaMc this PR when merged with the master branch will allow us to create, test and deploy Oncoscape as a container
=> Dockerize master

Dockerfile, Oncoscape/inst/scripts/apps/oncoscape/makefile, makefile
@LisaMc this PR when merged with the develop branch will allow us to create, test and deploy Oncoscape as a container
=> Dockerize develop

Oncoscape/makefile
@LisaMc Removed 1 occurrence of SVN in the develop branch, closes #41
=> Removed SVN commands from develop branch

Oncoscape/makefile, analysisPackages/makefile, dataPackages/makefile
@LisaMc Removed 15 occurrences of SVN in the master branch closes #41
=> Remove svn commands from master closes #41

INSTALL.md
@LisaMc  @pshannon-bioc I've updated and tested the documentation for the Linux and Mac OS X platforms.  To see what it looks like see: https://github.com/FredHutch/Oncoscape/blob/hotfix_master_INSTALL.md/INSTALL.md
These instructions have been tested agains the master branch by an external user for both the Linux and Mac OX platforms.
=> Updated INSTALL.md documentation

INSTALL.md
@LisaMc this is the same updated documentation that was already merged into master as a hotfix, now just updating develop branch to match.
=> updated INSTALL.md in develop branch

DOCKER.md, INSTALL.md
@LisaMc this is the same as PR #96 but targeting develop branch
=> Added docker documentation to develop branch

CONTRIBUTING.md
Changing 'Organised' to 'Organized' referencing "How is the code organized"
Question: Should the base for this simple change be in Master or Dev?
=> 'Organised' Spelling Correction

INSTALL.md, Oncoscape/inst/scripts/apps/oncoscape/makefile, makefile
@LisaMc updated INSTALL.md documentation to cover Windows (plus a little misc cleanup) and created Windows specific make targets to get Oncoscape running on Windows.  Tested and works on Windows 2008 and 2012R2.  Will create a PR for develop branch later today.
=> Windows platform updates - master

DOCKER.md
@LisaMc this PR completes the "Developing Oncoscape inside a Docker container" section of DOCKER.md and also includes some misc clean-up
=> updated docker documentation - master  

DOCKER.md
@LisaMc this PR completes the "Developing Oncoscape inside a Docker container" section of DOCKER.md and also includes some misc clean-up. same as PR #113 but targeting develop branch
=> updated docker documentation - develop

Dockerfile, circle.yml
@LisaMc I tweaked the docker config and added the circle.yml file required for circleci integration. After this is merged I'll link circleci to our repo.
=> circleci develop integration 

Dockerfile, circle.yml
@LisaMc same as PR #147 but for the master branch. I tweaked the docker config and added the circle.yml file required for circleci integration. After this is merged I'll link circleci to our repo.
=> circleci master integration 

Dockerfile
Changed install type and order of some commands
=> Updated Dockerfile - develop 

Dockerfile
updated Dockerfile, changed install type and switched order of some commands
=> Updated Dockerfile - master

Dockerfile, Oncoscape/R/wsPLSR.R, Oncoscape/inst/scripts/apps/oncoscape/makefile, circle.yml, makefile
Updated Dockerfile to perform a global install (make install vs make installLocal), added new 'citest' make target for automated remote testing, adjusted circle.yml to run the new citest target and implemented Lisa's fix of the wsPLSR.R bug that was preventing remote testing.
=> Fixed CI testing bug

dataPackages/TCGAlung/inst/extdata/manifest.tsv, dataPackages/TCGAlung/inst/unitTests/test_TCGAlung.R
variable names updated so _Agi added to mtx.mrna
=> fixed expression matrix naming in TCGAlung

Dockerfile, Oncoscape/R/wsPLSR.R, Oncoscape/inst/scripts/apps/oncoscape/makefile, README.md, circle.yml
Updated Dockerfile to perform a global install (make install vs make installLocal), adjusted circle.yml to run tests and implemented Lisa's fix of the wsPLSR.R bug that was preventing remote testing. Added CI status badge to README.md
=> Hotfix master ws plsr ci docker

README.md
Added a status badge to the README.md that will show the current status of the develop branch
=> Added Circle CI testing status badge

Dockerfile, circle.yml
Sucess on the build will now result in a push to the docker hub
=> CI deployment integration 

circle.yml
When develop branch is successfully built and tested on CircleCI it will now automatically be deployed to AWS
=> Added tutum deploy trigger

circle.yml
just a test change to trigger a redeploy
=> increased wait time before deploy trigger executed

circle.yml
Adjusting to trigger a new deploy
=> changed deploy sleep to 60

DOCKER.md
Tested this out on Windows 10 and it works fine. Docker indicates that Windows 10 is supported on their website, when I checked today.
=> Update DOCKER.md - Windows 10 works

circle.yml
Updating master's circle.yml file to update deploy trigger. This trigger will deploy Oncoscape to the new production environment in the cloud. Tutum has also been replaced with new Docker Cloud service.
=> hotfix_master_circleci_update  for new production environment

circle.yml
Updating develop's circle.yml file to update deploy trigger. This trigger will deploy Oncoscape to the new development environment in the cloud. Tutum has also been replaced with new Docker Cloud service.
=> hotfix_develop_circleci_updates for new environment

Oncoscape/inst/scripts/apps/oncoscape/widget.html, Oncoscape/inst/scripts/datasets/widget.html, Oncoscape/inst/scripts/index.common
Moved static content from lopez to an S3 bucket:
was: http://oncoscape.sttrcancer.org/oncoscape/*
now: http://oncoscape-static.s3-website-us-west-2.amazonaws.com/*
=> hotfix_master_static_content  - moving static content to S3

Oncoscape/inst/scripts/Dashboard/widget.html, Oncoscape/inst/scripts/apps/oncoscape/widget.html, Oncoscape/inst/scripts/index.common
Moved static content from lopez to an S3 bucket:
was: http://oncoscape.sttrcancer.org/oncoscape/*
now: http://oncoscape-static.s3-website-us-west-2.amazonaws.com/*
=> hotfix_develop_static_content - moving static content to S3

DOCKER.md, Dockerfile, INSTALL.md
updated INSTALL.md and DOCKER.md  but haven't tested docs yet.
=> update docs for node refactor

script/bootstrap, script/server, script/setup, script/test
script/bootstrap - install the prerequisities
script/setup - get the app ready to run
script/test - run the test suite
script/server - run the app
This this could use:
=> [WIP] initial pass at GitHub-style 'script' directory

Oncoscape/inst/scripts/Dashboard/widget.html
Master is updated to showcase the new beta site, includes a quick video and link to dev
video
@LisaMc
=> Prod front

server/app.js
=> Port Redirect

client/src/app/components/heatmap/heatmap.directive.js
and trigger rebuild for private data upload changes
=> filter heatmap tables for molecular

server/fileUpload.js
minor change to trigger rebuild for upload
=> schema def as lower case

server/app.routes.js, server/models/lookup.js
final testing of upload tool and redirects
=> deletes from lookup table upon project removal
